version: '3.8'
services:
  db:
    image: 'postgres:16-alpine'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5437:5432"
    restart: always
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=system
      - POSTGRES_PASSWORD=/run/secrets/db-password
      - POSTGRES_USER=userdb
    healthcheck:
      test: [ "CMD",  "pg_isready -d system -U userdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
secrets:
  db-password:
    file: app/db/password.txt

