services:
  db:
    image: 'postgres:16-alpine'
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=system
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=postgres
    ports:
      - 5436:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  data:
secrets:
  db-password:
    file: app/db/password.txt